### ISSUE TITLE
No badge on android

### ISSUE THREAD

**Issue by zarcode** [uuau99999/react-native-icon-badge#1]
Hi, thank you very much for sharing the library.
I have a problem with Android, what I do is only this:

```
const badgeHandlers = require("@uuau99999/react-native-icon-badge");
componentDidMount() {
        badgeHandlers.setIconBadge(3);
}
```
Badge on icon doen't show when I minimize the app.
I have done `react-native link` before `react-native run-android`.
`console.log(badgeHandlers);` shows me all the methods.
Its working on IOS but not on Android. I am trying it on Android 6.0 emulator.

**Comment by uuau99999** [comment]
Hello, @zarcode . May I ask about what is the simulator ROM that you're using? Cause Official Android ROM doesn't support badge icon and only Android release ROM which is developed by some particular manufactures support such feature. The Android badge implementation of this project is inspire by another awesome project which you can find here: 

 https://github.com/leolin310148/ShortcutBadger 

You can see that the Read.me of that project that mentions:

> IsBadgeWorking?
> A tool for displaying your device, launcher & android version and testing whether ShortcutBadger works or not may be downloaded from
> 
> Google Play https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking
> The GitHub repository https://github.com/leolin310148/IsBadgeWorking.Android/releases

You may like to check whether the current android version you're using is on the supporting list.

Hope this may help you.

**Comment by zarcode** [comment]
@uuau99999 Thank you, this cleared it out, it's because of Official Android ROM. Old one, seems new ones (android 8.0) support it. It's working on my Samsung and Huawei.

**Comment by luckyscjp** [comment]
Hello,

I tried but not showing app badges in android mobile. Please help me
